FROM php:7.2.2-apache

# Install mysqli extension and enable recommended apache modules
RUN docker-php-ext-install mysqli \
	&& a2enmod headers

# Ensure .htaccess files are respected by allowing overrides for the web root.
# We add a small conf file and enable it.
RUN printf "<Directory /var/www/html/>\n    AllowOverride All\n</Directory>\n" > /etc/apache2/conf-available/allow-override.conf \
	&& a2enconf allow-override

# Reduce information disclosure about Apache and remove Server header when possible.
# ServerTokens Prod keeps the Server header minimal ("Apache") while ServerSignature disables
# signatures on autogenerated error pages. We also unset the Server header via mod_headers
# at server config level so it's removed regardless of .htaccess availability.
RUN printf "ServerTokens Prod\nServerSignature Off\n" > /etc/apache2/conf-available/security.conf \
	&& printf "<IfModule mod_headers.c>\n    Header always unset Server\n</IfModule>\n" >> /etc/apache2/conf-available/security.conf \
	&& a2enconf security

# Expose port 80 (docker-compose handles published ports)
EXPOSE 80